# Generated by Django 4.2.30 on 2026-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fruit_name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='qspidersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=40)),
                ('marks', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
