# Generated by Django 4.2.30 on 2026-05-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('voter_id', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='FruitModel',
        ),
        migrations.DeleteModel(
            name='qspidersModel',
        ),
    ]
