# Generated by Django 4.2.30 on 2026-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_result_semester_remove_student_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(default='JVIT', max_length=150),
        ),
    ]
