# Generated by Django 4.2.30 on 2026-05-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_result_grade_alter_student_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
