# Generated by Django 4.2.30 on 2026-05-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
